process

diff --git a/0x05-processes_and_signals/100-process_and_pid_file b/0x05-processes_and_signals/100-process_and_pid_file
--- a/0x05-processes_and_signals/100-process_and_pid_file
+++ b/0x05-processes_and_signals/100-process_and_pid_file
@@ -1,19 +1,26 @@
 #!/usr/bin/env bash
-# This script creates the file /var/run/holbertonscript.pid containing its PID
-# Displays To infinity and beyond indefinitely
-# Displays I hate the kill command when receiving a SIGTERM signal
-# Displays Y U no love me?! when receiving a SIGINT signal
-# Deletes the file /var/run/holbertonscript.pid and terminate itself when receiving a SIGQUIT or SIGTERM signal
 
-function love() {
-    rm /var/run/holbertonscript.pid
+# Function to clean up and exit
+cleanup_and_exit() {
+    echo "Deleting PID file and terminating script..."
+    rm -f /var/run/myscript.pid
     exit
 }
 
-trap "echo I hate the kill command;love" SIGTERM
-trap "echo Y U no love me?!;love" SIGINT
+# Trap signals
+trap 'echo "I hate the kill command" && exit' SIGTERM
+trap 'echo "Y U no love me?!"' SIGINT
+trap 'cleanup_and_exit' SIGQUIT
 
-echo $$ >> /var/run/holbertonscript.pid
-while [ true ]; do
-    echo To infinity and beyond;
+# Get the PID and save it to the file
+echo $$ > /var/run/myscript.pid
+
+# Display the message indefinitely
+echo "To infinity and beyond indefinitely"
+
+# Wait for signals
+while true
+do
+    sleep 1
 done
+
